# Generated by Django 3.2 on 2023-05-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='media/pins'),
        ),
        migrations.AddField(
            model_name='pin',
            name='contentUrl',
            field=models.URLField(default=None),
        ),
    ]
