# Generated by Django 3.2 on 2023-05-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pin_contenturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='contentUrl',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
